#############################################################################
# Makefile for building: nugget
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  nugget.pro
# Template: app
# Command: /usr/local/lib/qt5/bin/qmake -o Makefile nugget.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WEBKITWIDGETS_LIB -DQT_WIDGETS_LIB -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -pthread -D_THREAD_SAFE -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -pthread -D_THREAD_SAFE -fPIE $(DEFINES)
INCPATH       = -I. -isystem /usr/local/include/qt5 -isystem /usr/local/include/qt5/QtWebKitWidgets -isystem /usr/local/include/qt5/QtWidgets -isystem /usr/local/include/qt5/QtWebKit -isystem /usr/local/include/qt5/QtGui -isystem /usr/local/include/qt5/QtNetwork -isystem /usr/local/include/qt5/QtCore -I. -I. -I/usr/local/lib/qt5/mkspecs/freebsd-clang
QMAKE         = /usr/local/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = nugget1.0.0
DISTDIR = /xj/waitman/nugget/.tmp/nugget1.0.0
LINK          = clang++
LFLAGS        = -pthread -Wl,-rpath,/usr/local/lib -Wl,-rpath-link,/usr/local/lib
LIBS          = $(SUBLIBS) -L/usr/local/lib -lQt5WebKitWidgets -lQt5Widgets -lQt5WebKit -lQt5Gui -lQt5Network -lQt5Core -lGL 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = /usr/local/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/local/lib/qt5/mkspecs/common/shell-unix.conf \
		/usr/local/lib/qt5/mkspecs/common/unix.conf \
		/usr/local/lib/qt5/mkspecs/common/freebsd.conf \
		/usr/local/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/local/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/lib/qt5/mkspecs/common/clang.conf \
		/usr/local/lib/qt5/mkspecs/qconfig.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_concurrent.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_core.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_dbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_gui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_multimedia.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_network.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_opengl.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_printsupport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_quick.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_webkit.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_widgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/local/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/local/lib/qt5/mkspecs/freebsd-clang/qmake.conf \
		/usr/local/lib/qt5/mkspecs/features/spec_post.prf \
		/usr/local/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/local/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/local/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/local/lib/qt5/mkspecs/features/default_post.prf \
		/usr/local/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/local/lib/qt5/mkspecs/features/qt.prf \
		/usr/local/lib/qt5/mkspecs/features/resources.prf \
		/usr/local/lib/qt5/mkspecs/features/moc.prf \
		/usr/local/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/local/lib/qt5/mkspecs/features/uic.prf \
		/usr/local/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/local/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/local/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/local/lib/qt5/mkspecs/features/yacc.prf \
		/usr/local/lib/qt5/mkspecs/features/lex.prf \
		nugget.pro mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = nugget
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = nugget


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_nugget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: nugget.pro /usr/local/lib/qt5/mkspecs/freebsd-clang/qmake.conf /usr/local/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/local/lib/qt5/mkspecs/common/shell-unix.conf \
		/usr/local/lib/qt5/mkspecs/common/unix.conf \
		/usr/local/lib/qt5/mkspecs/common/freebsd.conf \
		/usr/local/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/local/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/lib/qt5/mkspecs/common/clang.conf \
		/usr/local/lib/qt5/mkspecs/qconfig.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_concurrent.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_core.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_dbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_gui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_multimedia.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_network.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_opengl.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_printsupport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_quick.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_webkit.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_config_widgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/local/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/local/lib/qt5/mkspecs/freebsd-clang/qmake.conf \
		/usr/local/lib/qt5/mkspecs/features/spec_post.prf \
		/usr/local/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/local/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/local/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/local/lib/qt5/mkspecs/features/default_post.prf \
		/usr/local/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/local/lib/qt5/mkspecs/features/qt.prf \
		/usr/local/lib/qt5/mkspecs/features/resources.prf \
		/usr/local/lib/qt5/mkspecs/features/moc.prf \
		/usr/local/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/local/lib/qt5/mkspecs/features/uic.prf \
		/usr/local/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/local/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/local/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/local/lib/qt5/mkspecs/features/yacc.prf \
		/usr/local/lib/qt5/mkspecs/features/lex.prf \
		nugget.pro \
		/usr/local/lib/libQt5WebKitWidgets.prl \
		/usr/local/lib/libQt5WebKit.prl \
		/usr/local/lib/libQt5Gui.prl \
		/usr/local/lib/libQt5Core.prl \
		/usr/local/lib/libQt5Network.prl \
		/usr/local/lib/libQt5Widgets.prl
	$(QMAKE) -o Makefile nugget.pro
/usr/local/lib/qt5/mkspecs/features/spec_pre.prf:
/usr/local/lib/qt5/mkspecs/common/shell-unix.conf:
/usr/local/lib/qt5/mkspecs/common/unix.conf:
/usr/local/lib/qt5/mkspecs/common/freebsd.conf:
/usr/local/lib/qt5/mkspecs/common/gcc-base.conf:
/usr/local/lib/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/local/lib/qt5/mkspecs/common/clang.conf:
/usr/local/lib/qt5/mkspecs/qconfig.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_concurrent.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_core.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_dbus.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_gui.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_multimedia.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_network.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_opengl.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_printsupport.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_quick.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_webkit.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_config_widgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_declarative.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_declarative_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/lib/qt5/mkspecs/features/qt_functions.prf:
/usr/local/lib/qt5/mkspecs/features/qt_config.prf:
/usr/local/lib/qt5/mkspecs/freebsd-clang/qmake.conf:
/usr/local/lib/qt5/mkspecs/features/spec_post.prf:
/usr/local/lib/qt5/mkspecs/features/exclusive_builds.prf:
/usr/local/lib/qt5/mkspecs/features/default_pre.prf:
/usr/local/lib/qt5/mkspecs/features/resolve_config.prf:
/usr/local/lib/qt5/mkspecs/features/default_post.prf:
/usr/local/lib/qt5/mkspecs/features/warn_on.prf:
/usr/local/lib/qt5/mkspecs/features/qt.prf:
/usr/local/lib/qt5/mkspecs/features/resources.prf:
/usr/local/lib/qt5/mkspecs/features/moc.prf:
/usr/local/lib/qt5/mkspecs/features/unix/opengl.prf:
/usr/local/lib/qt5/mkspecs/features/uic.prf:
/usr/local/lib/qt5/mkspecs/features/unix/thread.prf:
/usr/local/lib/qt5/mkspecs/features/testcase_targets.prf:
/usr/local/lib/qt5/mkspecs/features/exceptions.prf:
/usr/local/lib/qt5/mkspecs/features/yacc.prf:
/usr/local/lib/qt5/mkspecs/features/lex.prf:
nugget.pro:
/usr/local/lib/libQt5WebKitWidgets.prl:
/usr/local/lib/libQt5WebKit.prl:
/usr/local/lib/libQt5Gui.prl:
/usr/local/lib/libQt5Core.prl:
/usr/local/lib/libQt5Network.prl:
/usr/local/lib/libQt5Widgets.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile nugget.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents nugget.ui $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/local/lib/qt5/bin/moc $(DEFINES) -I/usr/local/lib/qt5/mkspecs/freebsd-clang -I/xj/waitman/nugget -I/usr/local/include/qt5 -I/usr/local/include/qt5/QtWebKitWidgets -I/usr/local/include/qt5/QtWidgets -I/usr/local/include/qt5/QtWebKit -I/usr/local/include/qt5/QtGui -I/usr/local/include/qt5/QtNetwork -I/usr/local/include/qt5/QtCore -I/usr/local/include -I/usr/include/c++/v1 -I/usr/lib/clang/3.6.0/include -I/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_nugget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_nugget.h
ui_nugget.h: nugget.ui
	/usr/local/lib/qt5/bin/uic nugget.ui -o ui_nugget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_nugget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

